version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "16:30"
      timezone: "America/Vancouver"
    open-pull-requests-limit: 5

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "16:35"
      timezone: "America/Vancouver"
    open-pull-requests-limit: 5
